site_name: Notes radiologiques

nav:
  - index.md
  - Thorax:
    - EP/Ao: thorax/EP.md
    - Nodules: thorax/nodules.md
    - MÃ©diastin: thorax/mediastin.md
    - Kystes: thorax/kystes.md
    - Tabac: thorax/tabac.md
    - PID: thorax/PID.md
  - Femme:
    - EPP: femme/EPP.md
    - Ovaires: femme/ovaires.md
    - Seins: femme/seins.md
  - Uro:
    - Reins: uro/reins.md
    - Prostate: uro/prostate.md

theme:
  name: material
  language: fr
  palette:
    primary: grey
    accent: grey
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false

extra_css:
  - stylesheets/extra.css