site_name: Notes radiologiques

nav:
  - index.md
  - msk.md
  - Femme:
    - Urg: femme/urg.md
    - EPP: femme/EPP.md
    - Seins: femme/seins.md
    - Utérus: femme/uterus.md
    - Ovaires: femme/ovaires.md
    - Hystéro: femme/hystero.md
    - Prolapsus: femme/prolapsus.md
    - Pelviscanner: femme/pelviscanner.md
    - Malformations: femme/malformations.md
  - Thorax:
    - Urgences: thorax/ep.md
    - Nodules: thorax/nodules.md
    - Médiastin: thorax/mediastin.md
    - Infections: thorax/infections.md
    - Bronches: thorax/bronches.md
    - Cavités: thorax/cavites.md
    - Plèvre: thorax/plevre.md
    - Malfo: thorax/malfo.md
    - PID: thorax/PID.md
  - Cardio:
    - EI : cardio/EI.md
    - FA: cardio/FA.md
    - AAo: cardio/AAo.md
    - Malfo: cardio/malfo.md
    - Score CAC: cardio/cac.md
    - CAD-RADS: cardio/cadrads.md
  - Neuro:
    - Mort: neuro/mort.md
    - AVC: neuro/AVC.md
    - TC: neuro/TC.md
    - CR: neuro/CR.md
    - SEP: neuro/SEP.md
    - GBM: neuro/gbm.md
    - h/HTIC: neuro/HTIC.md
    - Parkinson: neuro/park.md
    - Démences: neuro/démences.md
    - Hypophyse: neuro/hypophyse.md
    - Pédiatrie: neuro/ped.md
  - ORL:
    - Amygdalite: ORL/amygdales.md
    - Tumeurs : ORL/tumeurs.md
    - Sinus: ORL/sinus.md
    - Pédiatrie: ORL/ped.md
  - Uro:
    - Reins: uro/reins.md
    - Vessie: uro/vessie.md
    - Greffon: uro/greffon.md
    - Lithiase: uro/lithiase.md
    - Prostate: uro/prostate.md
    - Ouraque: uro/ouraque.md
    - Lymphome: uro/lymphome.md
    - Dérivations: uro/derivations.md
    - Rétropéritoine: uro/retrope.md
    - Malformations: uro/malfo.md
  - Dig:
    - Foie: dig/foie.md
    - Rate: dig/rate.md
    - Grêle: dig/grele.md
    - RECIST: dig/RECIST.md
    - Pancréas: dig/pancreas.md
    - Surrénales: dig/surrénales.md
    - Caustique: dig/caustique.md
    - Urg péd: dig/pedia.md
  - Os:
    - Urgences: os/urgences.md
    - Fractures: os/fractures.md
    - Tumeurs: os/tumeurs.md
    - Rachis: os/rachis.md
    - MI: os/MI.md  
  - PDC: PDC.md
  - AVP: AVP.md
  - Outils:
    - Dose: outils/dose.md
    - Haller: outils/haller.md
    - RECIST: outils/recist.md
    - Cheson: outils/cheson.md
    - NASCET: outils/nascet.md
    - Volumes: outils/volumes.md
    - Fleischner: outils/fleischner.md
    - Biométrie neuropédiatrie: outils/biometrie.md

theme:
  name: material
  custom_dir: overrides
  language: fr
  palette:
    primary: grey
    accent: grey
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false

extra_css:
  - stylesheets/extra.css